IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/datasets'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/DCASE_experiments/domain_adaptation/exp2'
  PREMODEL_ROOT: '/home/hiroki/research/dcase2021_task2/input/PANNs/pre_trained_model/ResNet38_mAP=0.434.pth'
  
param:
  # feature
  sample_rate: 16000
  window_size: 1024
  hop_size: 512
  mel_bins: 128
  fmin: 60
  fmax: 7800
  # dataloader
  lr : 0.001
  batch_size : 128
  shuffle : True
  num_epochs : 50
  # etc
  devise : 'cuda'
  max_fpr : 0.1
